### ISSUE TITLE
Create a pure CSS file

### ISSUE THREAD

**Issue by deblynprado** [wpbrasil/PressStrap#3]
Some people (unfortunately) doesn't use SASS/Compass. Because of this it's necessary a simple .css file with the same structure of a compiled CSS.

I don't know if is possible made this with compass, the default for compass is clear the final CSS removing all declarations without a rule.

**Comment by fdaciuk** [comment]
If you are willing to change, Stylus has a `@css` directive. You can use literal CSS inside that :)

**Comment by deblynprado** [comment]
@fdaciuk I've never used Stylus. If it's possible do this with SASS/Compass I prefer.

If don't we can use Stylus tool

**Comment by fdaciuk** [comment]
I think this is impossible to do with SASS. By the way, with Stylus, you can do:

``` styl
@css {
  .container {}
}
```

That will compile to:

``` css
.container {}
```

Reference: http://learnboost.github.io/stylus/docs/literal.html

**Comment by claudiosanches** [comment]
To be honest, it would be better to do than trying to manually CSS.
Change the SASS for this to work would not be very good, besides that this solution Stylus also does not sound too beautiful for those who will use Stylus xD

**Comment by fdaciuk** [comment]
If I understood well, what the @deblynprado wants to do is provide 2 versions of the code: one with preprocessor and another without one, right?

But leaving out the preprocessor solves this problem :)

**Comment by nicholasio** [comment]
I think that's better leave the preprocessor instead of maintaining two versions of the code...

**Comment by deblynprado** [comment]
@fdaciuk this is the idea... provide two versions. If it's not possible I'm not gonna crazy.

I prefer the preprocessor because the maintenance in future is easier. But... unfortunately some people are not able to use this.

**Comment by fdaciuk** [comment]
Yep.. with preprocessor you can provide two versions, with just one code. To do this, I vote on Stylus xD
Simple and fast! :smile: :dancer: :dancer:

**Comment by deblynprado** [comment]
Maybe in a future version.
